include(CMakeFindDependencyMacro)
find_dependency(PocoFoundation)
find_dependency(PocoZip)
find_dependency(PocoUtil)
find_dependency(PocoXML)
include("${CMAKE_CURRENT_LIST_DIR}/PocoOSPTargets.cmake")
